import uniqid from "uniqid";

const ProductsDB = [
  {
    name: "iPhone 13",
    price: 1380,
    type: "Apple",
    colour: "Green",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Apple Watch",
    price: 400,
    type: "Apple",
    colour: "Black",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Google Cast",
    price: 200,
    type: "Google",
    colour: "Grey",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "iPod",
    price: 100,
    type: "Apple",
    colour: "Silver",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Samsung Pods",
    price: 100,
    type: "Samsung",
    colour: "Silver",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Amazon Nest",
    price: 100,
    type: "Amazon",
    colour: "Silver",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Razor Phone",
    price: 1380,
    type: "Razor",
    colour: "Green",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Blackberry",
    price: 1380,
    type: "Blackberry",
    colour: "Green",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Samsung Tablet",
    price: 1380,
    type: "Samsung",
    colour: "Green",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
];

export default ProductsDB;
