import uniqid from "uniqid";

const ProductsDB = [
  {
    name: "Apple",
    price: 1380,
    type: "Fruit",
    colour: "Red/Green",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Rice Bubbles",
    price: 400,
    type: "Cereal",
    colour: "White",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Stawberry",
    price: 200,
    type: "Fruit",
    colour: "Red",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Blueberry",
    price: 100,
    type: "Fruit",
    colour: "Blue",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Milk",
    price: 100,
    type: "Dairy",
    colour: "White",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Cheese",
    price: 100,
    type: "Dairy",
    colour: "Yellow",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Chocolate Milk",
    price: 1380,
    type: "Dairy",
    colour: "Brown",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Blackberry",
    price: 1380,
    type: "Blackberry",
    colour: "Black",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
  {
    name: "Weetbix",
    price: 1380,
    type: "Cereal",
    colour: "Brown",
    image: "",
    id: uniqid(),
    quantity: 1,
  },
];

export default ProductsDB;
